### ISSUE TITLE
Setup github Actions

### ISSUE THREAD

**Issue by gelencser09** [BME-MIT-IET/iet-hf-2023-test-and-rest#3]

**Comment by rajmunddongo** [comment]
I would do something like this:
```

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file java/pom.xml
```

You should upgrade the JDK version to your prefered version and change it to gradle  if you want to.
